kind: Service
apiVersion: v1
metadata:
  name: smartsense-gaia-x-api
spec:
  selector:
    app: smartsense-gaia-x-api
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 30016

---

apiVersion: v1
kind: Service
metadata:
  name: postgres # Sets service name
  labels:
    app: postgres # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 5432
  selector:
    app: postgres
